spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://pfm-2.crykxdrvy34n.eu-central-1.rds.amazonaws.com:5432/pfm
    username: postgres
    driver-class-name: org.postgresql.Driver
