server.port: 8081
spring:
  profiles: dev
  h2:
    console.enabled: true

rest.mapping:
  accountController: /accounts
  getAccountById: ${rest.mapping.accountController}/{id}
  updateAccount: ${rest.mapping.accountController}/{id}
  deleteAccount: ${rest.mapping.accountController}/{id}

logging:
  level:
    org:
      springframework: ERROR
  file: application.log
