#TODO - some of the properties can be moved to root file (here should be only overrides)
spring: # TODO - please add comments when which profile is intended to be used.
  h2:
    console.enabled: true
