spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5433/pfm4
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver