server.port: 8088

accessTokenExpiryTimeInMinutes: 1
refreshTokenExpiryTimeInMinutes: 10

spring:
  profiles:
    active: local-h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# TODO wrap log file for days
logging:
  pattern:
    console: "%d [%15.15t] [%36X{Correlation-Id}] %-5p %-30.30c{3}  - %m%n"
  level:
    com.pfm: INFO
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
  endpoint:
    health:
      show-details: always
