server.port: 8081
spring:
  h2:
    console.enabled: false
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate:
        ddl-auto: validate
  datasource:
      url: jdbc:mysql://localhost:5432/pfm
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework: ERROR
  file: application.log
