server.port: 8088
spring:
  profiles:
    active: local-h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d [%15.15t] [%36X{correlationId}] %-5p %-30.30c{3}  - %m%n"
  level:
    com.pfm: INFO
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    #  TODO log values in hibernate logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always